services:
  - type: web
    name: thebiolink
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "22.16.0"
      - key: MONGODB_URI
        sync: true
    disk:
      name: biolink-data
      mountPath: /var/data
      sizeGB: 1
